config/routes.rb
PowerProject::Application.routes.draw do

  

  resources :battery_models

 resources :accounting_offices

 resources :stations do
	  resources :batteries 
	  resources :rectifiers
		resources :generators
		
		collection do
			get 'list'			
		end
end

 resources :batteries do 
    get 'daily_report_list'
    get 'weekly_report_list'
        
    resources :battery_daily_tests do 
      post 'reports', :on => :collection
    end
	  resources :battery_weekly_tests do
			get 'jqgrid', :on => :collection 
			post 'reports', :on => :collection
		end
		resources :banks do
			post 'update_cell'	
		end
		
 end

	
	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users

  root :to => 'stations#index'

end

app/models/generator.rb
class Generator < ActiveRecord::Base

	# Inherits all the attributes of model Equipment
	acts_as :equipment, :as => :equipmentable

  attr_accessible :air_filter, :alternator_manufacturer, :alternator_model_no, :alternator_serial_no,
	:company_name, :control_panel_height, :control_panel_length, :control_panel_width, :cooling_type, 
	:engine_manufacturer, :engine_model_no, :engine_oil_type, :engine_serial_no, :eqp_code, :first_installation_date, 
	:fuel_filter,	:genset_height, :genset_length, :genset_weight, :installation_team, :model_no, :oil_sumo_capacity,
	:sec_fuel_filter, :sound_level, :starter_battery_capacity, :station_id, :system_type_id, :gen_type, :water_filter,
	:remarks

	validates :company_name, :presence => true
	
	belongs_to :station
	belongs_to :system_type
	
	# Display Team members name, from User IDs stored in installation_team field
	def team_members
		User.where(:id => self.installation_team.split(",")).pluck(:full_name).join(",")
	end
end

app/controllers/generators_controller.rb
class GeneratorsController < ApplicationController
	layout "tabbed_container"

  # GET /generators
  # GET /generators.json
  def index
    @generators = Generator.all
		@station = Station.find(params[:station_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @generators }
    end
  end

  # GET /generators/1
  # GET /generators/1.json
  def show
    @generator = Generator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @generator }
    end
  end

  # GET /generators/new
  # GET /generators/new.json
  def new
    @generator = Generator.new
		@station = Station.find(params[:station_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @generator }
    end
  end

  # GET /generators/1/edit
  def edit
    @generator = Generator.find(params[:id])
		@station = Station.find(params[:station_id])

		# Display users list for installation team
		installation_team = @generator.installation_team.split(",")
		@users = User.find(:all, :conditions => {:id => installation_team}, :select => 'name_emp_id, id').to_json.html_safe

  end

  # POST /generators
  # POST /generators.json
  def create
    @generator = Generator.new(params[:generator])
		@station = Station.find(params[:station_id])

		# Find system type id from system name
		@generator.system_type_id = SystemType.find_by_name(params[:generator][:system_type_id]).id

    respond_to do |format|
      if @generator.save

	      format.html { redirect_to station_generators_path(@generator.station), notice: 'Generator was successfully created.' }
        format.json { render json: @generator, status: :created, location: @generator }
      else
        format.html { render action: "new" }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /generators/1
  # PUT /generators/1.json
  def update
    @generator = Generator.find(params[:id])
		params[:generator][:system_type_id] = SystemType.find_by_name(params[:generator][:system_type_id]).id

    respond_to do |format|
      if @generator.update_attributes(params[:generator])
        format.html { redirect_to station_generators_path(@generator.station), notice: 'Generator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @generator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generators/1
  # DELETE /generators/1.json
  def destroy
    @generator = Generator.find(params[:id])
    @generator.destroy

    respond_to do |format|
      format.html { redirect_to station_generators_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/generators_helper.rb
module GeneratorsHelper
end

app/views/generators/_form.html.erb
<%= form_for([@station, @generator]) do |f| %>
  <% if @generator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@generator.errors.count, "error") %> prohibited this generator from being saved:</h2>

      <ul>
      <% @generator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :system_type %><br />
	  <%= f.select :system_type_id , system_types, :selected => (@generator.new_record? ? system_types.first : @generator.system_type.name ) %>
  </div>

  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :model_no %><br />
    <%= f.text_field :model_no, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
		<%= f.select :gen_type, ["Soundproof", "Canopy", "Open"] %>
  </div>
  <div class="field">
    <%= f.label :sound_level %><br />
    <%= f.text_field :sound_level, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :engine_manufacturer %><br />
    <%= f.text_field :engine_manufacturer, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :engine_model_no %><br />
    <%= f.text_field :engine_model_no, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :cooling_type %><br />
    <%= f.text_field :cooling_type, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :alternator_manufacturer %><br />
    <%= f.text_field :alternator_manufacturer, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :alternator_model_no %><br />
    <%= f.text_field :alternator_model_no, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :engine_oil_type %><br />
    <%= f.text_field :engine_oil_type, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :oil_sumo_capacity %><br />
    <%= f.text_field :oil_sumo_capacity, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :fuel_filter %><br />
    <%= f.text_field :fuel_filter, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :sec_fuel_filter %><br />
    <%= f.text_field :sec_fuel_filter, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :air_filter %><br />
    <%= f.text_field :air_filter, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :water_filter %><br />
    <%= f.text_field :water_filter, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :starter_battery_capacity %><br />
    <%= f.text_field :starter_battery_capacity, :size => 30 %>
  </div>

	<div class="field">
    <%= f.label :engine_serial_no %><br />
    <%= f.text_field :engine_serial_no, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :alternator_serial_no %><br />
    <%= f.text_field :alternator_serial_no, :size => 30 %>
  </div>
  <!--<div class="field">
    <%#= f.label :eqp_code %><br />
    <%#= f.text_field :eqp_code %>
  </div>-->
  <div class="field">
    <%= f.label :installation_team %><br />
    <%= f.text_field :installation_team, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :first_installation_date %><br />
    <%= f.date_select :first_installation_date %>
  </div>

	<div id="gen_dimensions" class="separator">
		<b>Generator Dimensions</b><span class="toggle">[ + ]</span>
		<div class="contents" style="display:none">
			<div class="field">
  	  	<%= f.label :genset_length %><br />
  	  	<%= f.number_field :genset_length, :size => 30 %>
  		</div>
  		<div class="field">
  	  	<%= f.label :genset_height %><br />
  	  	<%= f.number_field :genset_height, :size => 30 %>
  		</div>
  		<div class="field">
  	  	<%= f.label :genset_weight %><br />
  	  	<%= f.number_field :genset_weight, :size => 30 %>
 		 	</div>
		</div>
	</div>
  
	<div id="cpanel_dimensions" class="separator">
		<b>Control Panel Dimensions </b><span class="toggle">[ + ]</span>
		<div class="contents" style="display:none">
			<div class="field">
  		  <%= f.label :control_panel_length %><br />
  		  <%= f.number_field :control_panel_length, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label :control_panel_width %><br />
   		 	<%= f.number_field :control_panel_width, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label :control_panel_height %><br />
   		 	<%= f.number_field :control_panel_height, :size => 30 %>
  		</div>
		</div>	 
	</div>

	<div id="gen_supplier_details" class="separator">
		<b>Supplier and local agent details </b><span  class="toggle">[ + ]</span>
		<div class="contents" style="display:none">
			<div class="field">
  		  <%= f.label "Supplier Company Name" %><br />
  		  <%= f.text_field :supp_company_name, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label "Supplier Company Address" %><br />
   		 	<%= f.text_field :supp_company_address, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label "Supplier Company Phone" %><br />
   		 	<%= f.text_field :supp_company_phone, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label "Supplier Company Fax" %><br />
   		 	<%= f.text_field :supp_company_fax, :size => 30 %>
  		</div>
  		<div class="field">
   		 	<%= f.label "Supplier Remarks" %><br />
   		 	<%= f.text_area :supp_remarks, :rows => 8, :cols => 43 %>
  		</div>
  		<div class="field">
   		 	<%= f.label "Current Local Agent Name" %><br />
   		 	<%= f.text_field :curr_local_agent_name, :size => 30 %>
  		</div>
			<div class="field">
   		 	<%= f.label "Local Agent Contact Person" %><br />
   		 	<%= f.text_field :local_agent_contact_person, :size => 30 %>
  		</div>
			<div class="field">
   		 	<%= f.label "Local Agent Contact Person mobile no" %><br />
   		 	<%= f.text_field :local_agent_mobile, :size => 30 %>
  		</div>
			<div class="field">
   		 	<%= f.label "Local Agent Office Phone no" %><br />
   		 	<%= f.text_field :local_agent_office_phone, :size => 30 %>
  		</div>
			<div class="field">
   		 	<%= f.label "Local Agent Office Fax no" %><br />
   		 	<%= f.text_field :local_agent_office_fax, :size => 30 %>
  		</div>
		</div>	 
	</div>

  <div class="field">
    <%= f.label :remarks %><br />
    <%= f.text_area :remarks, :rows => 8, :cols => 43 %>
  </div>
	<%= f.hidden_field :station_id, :value => @station.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
	// Observer to display cpanel dimensions on click
	$("#cpanel_dimensions span").click(function() {
		$("#cpanel_dimensions div.contents").is(":visible") ? $(this).html("[ + ]") : $(this).html("[ - ]");
		$("#cpanel_dimensions div.contents").slideToggle('slow');
	});

	// Observer to display generator dimensions on click
	$("#gen_dimensions span").click(function() {
		$("#gen_dimensions div.contents").is(":visible") ? $(this).html("[ + ]") : $(this).html("[ - ]");
		$("#gen_dimensions div.contents").slideToggle('slow');
	});

	// Observer to display generator dimensions on click
	$("#gen_supplier_details span").click(function() {
		$("#gen_supplier_details div.contents").is(":visible") ? $(this).html("[ + ]") : $(this).html("[ - ]");
		$("#gen_supplier_details div.contents").slideToggle('slow');
	});

// Show installation team by name
	var prePopulateData = <%= @users %>

	$("#generator_installation_team").tokenInput("/users?from=team",{hintText: "Enter name here", theme: "facebook", 	
		propertyToSearch: "name_emp_id", prePopulate: prePopulateData});

</script>

app/views/generators/edit.html.erb
<h1>Editing generator</h1>

<%= render 'form' %>

<%= link_to 'Back', station_generators_path(@station) %>

app/views/generators/index.html.erb
<h1>Listing generators</h1>
<% count = 1 
@station.generators.each do |generator| %>
<h2> Generator #<%= count %> </h2>
<div class="eqp_detail">
	<div class="leftdiv">System type </div>
	<div class="rightdiv"><%= generator.system_type.name %></div>
	<div class="leftdiv">Company name</div>
	<div class="rightdiv"><%= generator.company_name %></div>
	<div class="leftdiv">Model no</div>
	<div class="rightdiv"><%= generator.model_no %></div>
	<div class="leftdiv">Generator type</div>
	<div class="rightdiv"><%= generator.gen_type %></div>
	<div class="leftdiv">Sound level</div>
	<div class="rightdiv"><%= generator.sound_level %></div>
	<div class="leftdiv">Engine manufacturer</div>
	<div class="rightdiv"><%= generator.engine_manufacturer %></div>
	<div class="leftdiv">Engine Model no</div>
	<div class="rightdiv"><%= generator.engine_model_no %></div>
	<div class="leftdiv">Cooling type</div>
	<div class="rightdiv"><%= generator.cooling_type %></div>
	<div class="leftdiv">Alternator manufacturer</div>
	<div class="rightdiv"><%= generator.alternator_manufacturer %></div>
	<div class="leftdiv">Alternator model no</div>
	<div class="rightdiv"><%= generator.alternator_model_no %></div>
	<div class="leftdiv">Engine oil type</div>
	<div class="rightdiv"><%= generator.engine_oil_type %></div>
	<div class="leftdiv">Oil sumo capacity</div>
	<div class="rightdiv"><%= generator.oil_sumo_capacity %></div>
	<div class="leftdiv">Dimension</div>
	<div class="rightdiv">Length: <%= generator.genset_length %> Height: <%= generator.genset_height %> Weight: <%= generator.genset_weight %></div>
	<div class="leftdiv">Starter battery capacity</div>
	<div class="rightdiv"><%= generator.starter_battery_capacity %></div>
	<div class="leftdiv">Control panel dimension</div>
	<div class="rightdiv">Length: <%= generator.control_panel_length %> Height: <%= generator.control_panel_height %> Width: <%= generator.control_panel_width %> </div>
	<div class="leftdiv">Engine serial no</div>
	<div class="rightdiv"><%= generator.engine_serial_no %></div>
	<div class="leftdiv">Alternator serial no</div>
	<div class="rightdiv"><%= generator.alternator_serial_no %></div>
	<div class="leftdiv">Alternator serial no</div>
	<div class="rightdiv"><%= generator.alternator_serial_no %></div>
	<div class="leftdiv">Installation Team </div>
	<div class="rightdiv"><%= team_members(generator) %></div>
	<div class="leftdiv">First installation date </div>
	<div class="rightdiv"><%= generator.first_installation_date %></div>
	<div class="leftdiv"> Remarks </div>
	<div class="rightdiv"><%= generator.remarks %></div>
</div>

<div class="eqp_supplier_detail"> 
	<fieldset>
	<legend>Supplier and Local agent  details</legend>
	<div class="leftdiv">Supplier Company Name</div>
	<div class="rightdiv"><%= generator.supp_company_name %></div> 
	<div class="leftdiv">Supplier Company Address</div>
	<div class="rightdiv"><%= generator.supp_company_address %></div> 
	<div class="leftdiv">Supplier Company Office</div>
	<div class="rightdiv">Phone: <%= generator.supp_company_phone %>, Fax: <%= generator.supp_company_fax %> </div> 
	<div class="leftdiv">Remarks</div>
	<div class="rightdiv"><%= generator.supp_remarks %></div> 
	<div class="leftdiv">Current Local Agent Name</div>
	<div class="rightdiv"><%= generator.curr_local_agent_name %></div> 
	<div class="leftdiv">Local Agent Contact Person</div>
	<div class="rightdiv"><%= generator.local_agent_contact_person %> <%= generator.local_agent_mobile %></div> 
	<div class="leftdiv">Local Agent Office </div>
	<div class="rightdiv"> Phone : <%= generator.local_agent_office_phone %>, Fax <%= generator.local_agent_office_fax %></div> 
</div>
<div style="clear:both">
	<%= link_to_if(can?(:edit, Generator), "Edit", edit_station_generator_path(@station, generator)) {} %> |
	<%= link_to_if(can?(:delete, Generator), "Delete", station_generator_path(@station, generator), method: :delete, 	
	data: { confirm: 'Are you sure?' }) {} %>
</div>
<% count  += 1 end %>

<br />

<%= link_to_if(can?(:new, Generator), 'New Generator', new_station_generator_path(@station)) {} %>

app/views/generators/new.html.erb
<h1>New generator</h1>

<%= render 'form' %>

app/views/generators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company name:</b>
  <%= @generator.company_name %>
</p>

<p>
  <b>Model no:</b>
  <%= @generator.model_no %>
</p>

<p>
  <b>Type:</b>
  <%= @generator.type %>
</p>

<p>
  <b>Sound level:</b>
  <%= @generator.sound_level %>
</p>

<p>
  <b>Engine manufacturer:</b>
  <%= @generator.engine_manufacturer %>
</p>

<p>
  <b>Engine model no:</b>
  <%= @generator.engine_model_no %>
</p>

<p>
  <b>Cooling type:</b>
  <%= @generator.cooling_type %>
</p>

<p>
  <b>Alternator manufacturer:</b>
  <%= @generator.alternator_manufacturer %>
</p>

<p>
  <b>Alternator model no:</b>
  <%= @generator.alternator_model_no %>
</p>

<p>
  <b>Engine oil type:</b>
  <%= @generator.engine_oil_type %>
</p>

<p>
  <b>Oil sumo capacity:</b>
  <%= @generator.oil_sumo_capacity %>
</p>

<p>
  <b>Fuel filter:</b>
  <%= @generator.fuel_filter %>
</p>

<p>
  <b>Sec fuel filter:</b>
  <%= @generator.sec_fuel_filter %>
</p>

<p>
  <b>Air filter:</b>
  <%= @generator.air_filter %>
</p>

<p>
  <b>Water filter:</b>
  <%= @generator.water_filter %>
</p>

<p>
  <b>Genset length:</b>
  <%= @generator.genset_length %>
</p>

<p>
  <b>Genset height:</b>
  <%= @generator.genset_height %>
</p>

<p>
  <b>Genset weight:</b>
  <%= @generator.genset_weight %>
</p>

<p>
  <b>Starter battery capacity:</b>
  <%= @generator.starter_battery_capacity %>
</p>

<p>
  <b>Control panel length:</b>
  <%= @generator.control_panel_length %>
</p>

<p>
  <b>Control panel width:</b>
  <%= @generator.control_panel_width %>
</p>

<p>
  <b>Control panel height:</b>
  <%= @generator.control_panel_height %>
</p>

<p>
  <b>Engine serial no:</b>
  <%= @generator.engine_serial_no %>
</p>

<p>
  <b>Alternator serial no:</b>
  <%= @generator.alternator_serial_no %>
</p>

<p>
  <b>Eqp code:</b>
  <%= @generator.eqp_code %>
</p>

<p>
  <b>System type:</b>
  <%= @generator.system_type_id %>
</p>

<p>
  <b>Station:</b>
  <%= @generator.station_id %>
</p>

<p>
  <b>Installation team:</b>
  <%= @generator.installation_team %>
</p>

<p>
  <b>First installation date:</b>
  <%= @generator.first_installation_date %>
</p>


<%= link_to 'Edit', edit_generator_path(@generator) %> |
<%= link_to 'Back', generators_path %>