config/routes.rb
PowerProject::Application.routes.draw do

  

  resources :battery_models

 resources :accounting_offices

 resources :stations do
	  resources :batteries 
	  resources :rectifiers
		resources :generators
		
		collection do
			get 'list'			
		end
end

 resources :batteries do 
    get 'daily_report_list'
    get 'weekly_report_list'
        
    resources :battery_daily_tests do 
      post 'reports', :on => :collection
    end
	  resources :battery_weekly_tests do
			get 'jqgrid', :on => :collection 
			post 'reports', :on => :collection
		end
		resources :banks do
			post 'update_cell'	
		end
		
 end

	
	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users

  root :to => 'stations#index'

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  attr_accessible :battery_id, :cells, :total_voltage, :visual_inpsection
	
	belongs_to :battery
	has_many :cells, :dependent => :destroy
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banks }
    end
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
    @bank = Bank.find(params[:id])

		# Prepare row data to be passed into jqgrid as json
		@row_data = Array.new
  	@bank.cells.each_with_index do |v, i| 
			cell = Hash.new
			cell[:id] = i.to_i + 1
			cell[:cell_voltage] = v
			@row_data.push(cell)
		end
		#@row_data = [{:id => 1, :cell_voltage => 12}, {:id => 2, :cell_voltage => 24}]
		
		respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @row_data }
    end
  end

  # GET /banks/new
  # GET /banks/new.json
  def new
    @bank = Bank.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bank }
    end
  end

  # GET /banks/1/edit
  def edit
    @bank = Bank.find(params[:id])
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(params[:bank])

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render json: @bank, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banks/1
  # PUT /banks/1.json
  def update
    @bank = Bank.find(params[:id])

    respond_to do |format|
      if @bank.update_attributes(params[:bank])
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to banks_url }
      format.json { head :no_content }
    end
  end

	# Custom action added for entering cell voltage from jqgrid
	# POST /batteries/1/banks/1/update_cell
  # POST /banks/1.json
  def update_cell
    @bank = Bank.find(params[:bank_id])
		cells = @bank.cells
		cells[params[:id].to_i - 1] = params[:cell_voltage].to_i
		puts "@@@@@@cells is #{cells.inspect}" 
    respond_to do |format|
      if @bank.update_attributes(:cells => cells)
        #format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
				#render :text => "saved"        
				format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_voltage %><br />
    <%= f.text_field :total_voltage %>
  </div>
  <div class="field">
    <%= f.label :visual_inpsection %><br />
    <%= f.text_area :visual_inpsection %>
  </div>
  <div class="field">
    <%= f.label :cells %><br />
    <%= f.text_area :cells %>
  </div>
  <div class="field">
    <%= f.label :battery_id %><br />
    <%= f.number_field :battery_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<h1>Listing banks</h1>

<table class="power">
  <tr>
    <th>Total voltage</th>
    <th>Visual inpsection</th>
    <th>Cells</th>
    <th>Battery</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banks.each do |bank| %>
  <tr>
    <td><%= bank.total_voltage %></td>
    <td><%= bank.visual_inpsection %></td>
    <td><%= bank.cells %></td>
    <td><%= bank.battery_id %></td>
    <td><%= link_to 'Show', bank %></td>
    <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
    <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Total voltage:</b>
  <%= @bank.total_voltage %>
</p>

<p>
  <b>Visual inpsection:</b>
  <%= @bank.visual_inpsection %>
</p>

<p>
  <b>Cells:</b>
  <%= @bank.cells %>
</p>

<p>
  <b>Battery:</b>
  <%= @bank.battery_id %>
</p>


<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>

app/views/banks/view.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>

   <%= javascript_include_tag 'dhtmlx/dhtmlxcommon.js' %>
        <%= javascript_include_tag 'dhtmlx/dhtmlxgrid.js' %>
        <%= javascript_include_tag 'dhtmlx/dhtmlxgridcell.js' %>
        <%= javascript_include_tag 'dhtmlx/dhtmlxdataprocessor.js' %>

        <%= stylesheet_link_tag 'dhtmlx/dhtmlxgrid.css' %>
        <%= stylesheet_link_tag 'dhtmlx/skins/dhtmlxgrid_dhx_skyblue.css' %>
<script>


    </head>
    <body>
     <div id="grid_here" style="width:600px; height:400px;">
        </div>
        <script type="text/javascript" charset="utf-8">
            var grid = new dhtmlXGridObject("grid_here");
            //grid.setImagePath("/javascripts/codebase/imgs/");
						grid.setImagePath("/images/dhtmlx/imgs/");

            grid.setHeader("Cell no, Cell Voltage");
            grid.setInitWidths("100,100,*");
            grid.setSkin("dhx_skyblue");
            grid.init();

						dp = new dataProcessor("/batteries/1/banks/dbaction.xml");

            dp.init(grid);


        </script>
        <input type="button" value="Add" onclick="grid.addRow(grid.uid(),'cell entry')">
        <input type="button" value="Delete" onclick="grid.deleteSelectedRows()">




    </body>
</html>