config/routes.rb
PowerProject::Application.routes.draw do

  

  resources :battery_models

 resources :accounting_offices

 resources :stations do
	  resources :batteries 
	  resources :rectifiers
		resources :generators
		
		collection do
			get 'list'			
		end
end

 resources :batteries do 
    get 'daily_report_list'
    get 'weekly_report_list'
        
    resources :battery_daily_tests do 
      post 'reports', :on => :collection
    end
	  resources :battery_weekly_tests do
			get 'jqgrid', :on => :collection 
			post 'reports', :on => :collection
		end
		resources :banks do
			post 'update_cell'	
		end
		
 end

	
	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users

  root :to => 'stations#index'

end

app/models/accounting_office.rb
class AccountingOffice < ActiveRecord::Base
  attr_accessible :name, :regional_directorate_id
  
  validates :name, :presence => true, :uniqueness => true

	
	belongs_to :regional_directorate
	has_many :stations
end

app/controllers/accounting_offices_controller.rb
class AccountingOfficesController < ApplicationController
  # GET /accounting_offices
  # GET /accounting_offices.json
  def index
    
		# Reqeust is for listing acc_offices under selected Regional Directorate(RD)
		if params[:from] && params[:reg_directorate] != 'ALL'
			@accounting_offices = RegionalDirectorate.find(params[:reg_directorate]).accounting_offices 
		else
			@accounting_offices =  AccountingOffice.all
		end

		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounting_offices }
    end
  end

  # GET /accounting_offices/1
  # GET /accounting_offices/1.json
  def show
    @accounting_office = AccountingOffice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @accounting_office }
    end
  end

  # GET /accounting_offices/new
  # GET /accounting_offices/new.json
  def new
    @accounting_office = AccountingOffice.new
    @regional_directorates = RegionalDirectorate.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @accounting_office }
    end
  end

  # GET /accounting_offices/1/edit
  def edit
    @accounting_office = AccountingOffice.find(params[:id])
    @regional_directorates = RegionalDirectorate.all

  end

  # POST /accounting_offices
  # POST /accounting_offices.json
  def create
    @accounting_office = AccountingOffice.new(params[:accounting_office])

    #@accounting_office.regional_directorate_id = RegionalDirectorate.find_by_code(params[:accounting_office][:regional_directorate_id]).id

    respond_to do |format|
      if @accounting_office.save
        format.html { redirect_to @accounting_office, notice: 'Accounting office was successfully created.' }
        format.json { render json: @accounting_office, status: :created, location: @accounting_office }
      else
        format.html { render action: "new" }
        format.json { render json: @accounting_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounting_offices/1
  # PUT /accounting_offices/1.json
  def update
    @accounting_office = AccountingOffice.find(params[:id])

    respond_to do |format|
      if @accounting_office.update_attributes(params[:accounting_office])
        format.html { redirect_to @accounting_office, notice: 'Accounting office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @accounting_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting_offices/1
  # DELETE /accounting_offices/1.json
  def destroy
    @accounting_office = AccountingOffice.find(params[:id])
    @accounting_office.destroy

    respond_to do |format|
      format.html { redirect_to accounting_offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accounting_offices_helper.rb
module AccountingOfficesHelper
end

app/views/accounting_offices/_form.html.erb
<%= form_for(@accounting_office) do |f| %>
  <% if @accounting_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accounting_office.errors.count, "error") %> prohibited this accounting_office from being saved:</h2>

      <ul>
      <% @accounting_office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :regional_directorate_id %><br />
	<%= f.collection_select :regional_directorate_id , @regional_directorates, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounting_offices/edit.html.erb
<h1>Editing accounting_office</h1>

<%= render 'form' %>

<%= link_to 'Show', @accounting_office %> |
<%= link_to 'Back', accounting_offices_path %>

app/views/accounting_offices/index.html.erb
<h1>Listing accounting offices</h1>

<table class="power"
  <tr>
    <th>Name</th>
    <th>Regional directorate</th>
    <th></th>
    <th></th>
  </tr>

<% @accounting_offices.each do |accounting_office| %>
  <tr>
    <td><%= accounting_office.name %></td>
    <td><%= accounting_office.regional_directorate.name %></td>
    <td><%= link_to_if(can?(:edit, AccountingOffice), 'Edit', edit_accounting_office_path(accounting_office)) {} %></td>
    <td><%= link_to_if(can?(:delete, AccountingOffice),'Delete', accounting_office, method: :delete, data: { confirm: 'Are you sure?' }) {} %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Accounting office', new_accounting_office_path %>

app/views/accounting_offices/new.html.erb
<h1>New accounting_office</h1>

<%= render 'form' %>

<%= link_to 'Back', accounting_offices_path %>

app/views/accounting_offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @accounting_office.name %>
</p>

<p>
  <b>Regional directorate:</b>
  <%= @accounting_office.regional_directorate.name %>
</p>


<%= link_to 'Edit', edit_accounting_office_path(@accounting_office) %> |
<%= link_to 'Back', accounting_offices_path %>