config/routes.rb
PowerProject::Application.routes.draw do

  

  resources :battery_models

 resources :accounting_offices

 resources :stations do
	  resources :batteries 
	  resources :rectifiers
		resources :generators
		
		collection do
			get 'list'			
		end
end

 resources :batteries do 
    get 'daily_report_list'
    get 'weekly_report_list'
        
    resources :battery_daily_tests do 
      post 'reports', :on => :collection
    end
	  resources :battery_weekly_tests do
			get 'jqgrid', :on => :collection 
			post 'reports', :on => :collection
		end
		resources :banks do
			post 'update_cell'	
		end
		
 end

	
	devise_for :users, :controllers => { :registrations => "registrations" }
	resources :users

  root :to => 'stations#index'

end

app/views/layouts/_header.html.erb
<div id="header">
	<div id="header_left">
		<img src="/images/ntlogo.png" alt="Nepal Telecom"/>
	</div>
	<div id="header_right">
	<% if  user_signed_in? %>
		Welcome, <%= current_user.email %> <br />
		<%= link_to "Change Password", edit_user_registration_path %> | <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> 
		
	<% end %>
	</div>
	
	<div id="header_mid">
		<h1> Power Management Support System </h1>
		<h2> Power Department, Chhauni </h2>
	</div>
	
	
</div>
<div class="greenline"></div>

	

app/views/layouts/_sidebar.html.erb
<div id="side_bar">
	<h3 class="subhead">Overview Modules</h3>
	<ul>
		<li><%= link_to_if(can?(:read, AccountingOffice), "List Accounting Offices", accounting_offices_path) {} %></li>
		<li><%= link_to "List Stations", stations_path %></li>
		<li><%= link_to_if(can?(:read, User), "List Users", users_path ) {} %>  </li>
		<li><%= link_to_if(can?(:read, BatteryModel), "List Battery Models", battery_models_path ) {}  %></li>
	</ul>

	<% if current_user.role? :admin %>
		<h3 class="subhead">Admin Modules</h3>
		<ul>
			<li> <%= link_to "Add Accounting Office", new_accounting_office_path %> </li>
			<li> <%= link_to "Add Station", new_station_path %>  </li>
			<li> <%= link_to "Add User", new_user_path %> </li>
			<li> <%= link_to "Add Battery Model", new_battery_model_path %> </li>

		</ul>
	<% end %>

	<!-- <h3 class="subhead">Reporting Modules</h3>
	<ul>
		<li><a href="">Daily Report</a></li>
		<li><a href="">Weekly Report</a></li>
		<li><a href="">Search Station</a></li>
		<li><a href="">Error Report</a></li>
	</ul> -->
		
</div>

app/views/layouts/_station_brief.html.erb
		<div id = "stations_overview">
			<div> <span  class="heading"> <%= @station.name %> </span>  <span class="icon"> <img src="/assets/arrow-right.png" class="heading"></img>  </span> </div>
			<div class="box"  style="display:none" >
			  <div class="leftdiv">Incharge name</div>
			  <div class="rightdiv">: <%= @station.inc_name %></div><br />
  
			  <div class="leftdiv">Incharge cell number</div>
			  <div class="rightdiv">: <%= @station.inc_cell %></div><br />
	  	
			  <div class="leftdiv">Incharge Address</div>
			  <div class="rightdiv">: <%= @station.inc_address %></div><br />
	  
			  <div class="leftdiv">Regional Directorate</div>
			  <div class="rightdiv">: <%= @station.regional_directorate.name %></div><br />
	   		
				<div class="leftdiv">Accounting Office </div>
			  <div class="rightdiv">: <%= @station.accounting_office.name %></div><br />
	  
			  <!-- <div class="leftdiv">Zone/ District/ City</div> -->
			  <!-- <div class="rightdiv">: <%#= @station.regional_directorate.zone %>, <%#= @station.regional_directorate.district %>, <%#= @station.regional_directorate.city %></div><br /> -->
	  
			  <div class="leftdiv">Remarks</div>
			  <div class="rightdiv">: <%= @station.remarks %></div><br />
  	
			</div>
		</div>

		<h1>Equipment details </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Power Management Support System</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render :partial => "layouts/header" %>
<div id="container">
	<% if  user_signed_in? %>
		<%= render :partial => "layouts/sidebar" %>
	<% end %>
	<div id="content">
		<%= yield %>
	</div>	
</div>
</body>

</html>

app/views/layouts/tabbed_container.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Power Maintenance Management System</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render :partial => "layouts/header" %>
<div id="container">
	<% if  user_signed_in? %>
		<%= render :partial => "layouts/sidebar" %>
	<% end %>

	<div id="content">
		<%= render :partial => "layouts/station_brief" %>
		<%= tabs %>
		<div id ="tabbed_content">
			<%= yield %>
		</div>
	</div>	

</div>
</body>

</html>